name: base
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - anaconda-anon-usage=0.7.5
  - anaconda-auth=0.12.3
  - anaconda-cli-base=0.7.0
  - annotated-types=0.6.0
  - archspec=0.2.5
  - boltons=25.0.0
  - brotlicffi=1.2.0.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.12.2
  - certifi=2025.11.12
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - click=8.2.1
  - conda=25.11.1
  - conda-anaconda-telemetry=0.3.0
  - conda-anaconda-tos=0.2.2
  - conda-content-trust=0.2.0
  - conda-libmamba-solver=25.11.0
  - conda-package-handling=2.4.0
  - conda-package-streaming=0.12.0
  - cpp-expected=1.1.0
  - cryptography=46.0.3
  - dbus=1.16.2
  - distro=1.9.0
  - expat=2.7.3
  - fmt=11.2.0
  - frozendict=2.4.6
  - gettext=0.21.0
  - icu=73.1
  - idna=3.11
  - jansson=2.14
  - jaraco.classes=3.4.0
  - jaraco.context=6.0.0
  - jaraco.functools=4.1.0
  - jeepney=0.7.1
  - jsonpatch=1.33
  - jsonpointer=3.0.0
  - keyring=25.7.0
  - ld_impl_linux-64=2.44
  - libarchive=3.8.2
  - libcurl=8.16.0
  - libev=4.33
  - libexpat=2.7.3
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libiconv=1.16
  - libidn2=2.3.8
  - libmamba=2.3.2
  - libmambapy=2.3.2
  - libmpdec=4.0.0
  - libnghttp2=1.67.1
  - libsolv=0.7.30
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libunistring=1.3
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libxml2=2.13.9
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - markdown-it-py=4.0.0
  - mdurl=0.1.2
  - menuinst=2.4.2
  - more-itertools=10.8.0
  - msgpack-python=1.1.1
  - ncurses=6.5
  - nlohmann_json=3.11.2
  - openssl=3.0.18
  - packaging=25.0
  - pcre2=10.46
  - pip=25.3
  - pkce=1.0.3
  - platformdirs=4.5.0
  - pluggy=1.5.0
  - pthread-stubs=0.3
  - pybind11-abi=5
  - pycosat=0.6.6
  - pycparser=2.23
  - pydantic=2.12.4
  - pydantic-core=2.41.5
  - pydantic-settings=2.12.0
  - pygments=2.19.2
  - pyjwt=2.10.1
  - pysocks=1.7.1
  - python=3.13.11
  - python-dotenv=1.1.0
  - python_abi=3.13
  - readchar=4.2.1
  - readline=8.3
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - requests=2.32.5
  - rich=14.2.0
  - ruamel.yaml=0.18.16
  - ruamel.yaml.clib=0.2.14
  - secretstorage=3.4.0
  - semver=3.0.4
  - setuptools=80.9.0
  - shellingham=1.5.4
  - simdjson=3.10.1
  - sqlite=3.51.0
  - tk=8.6.15
  - tomli=2.2.1
  - tqdm=4.67.1
  - truststore=0.10.1
  - typer=0.20.0
  - typer-slim=0.20.0
  - typer-slim-standard=0.20.0
  - typing-extensions=4.15.0
  - typing-inspection=0.4.2
  - typing_extensions=4.15.0
  - tzdata=2025b
  - urllib3=2.6.1
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - yaml-cpp=0.8.0
  - zlib=1.3.1
  - zstandard=0.24.0
  - zstd=1.5.7
  - pip:
      - contourpy==1.3.3
      - cycler==0.12.1
      - decorator==4.4.2
      - et-xmlfile==2.0.0
      - fonttools==4.61.1
      - imageio==2.37.2
      - imageio-ffmpeg==0.6.0
      - kiwisolver==1.4.9
      - matplotlib==3.10.8
      - moviepy==1.0.3
      - numpy==2.4.2
      - opencv-python==4.13.0.90
      - openpyxl==3.1.5
      - pandas==3.0.0
      - pillow==11.3.0
      - proglog==0.1.12
      - pyparsing==3.3.2
      - python-dateutil==2.9.0.post0
      - scipy==1.17.0
      - six==1.17.0
      - syncstart==1.1.1
prefix: /home/zihan/miniconda3
